### ISSUE TITLE
[1.18.2] Crash when entering Nether 

### ISSUE THREAD

**Issue by Partonetrain** [immortius/chunkbychunk#30] opened 2022-11-14 20:28 UTC
To reproduce, make a Nether Portal in the overworld and enter it.
Don't know if it makes a difference, but I have the config option `synch_nether_chunk_spawn = true`

```
java.lang.ArrayIndexOutOfBoundsException: Index 16 out of bounds for length 16
	at xyz.immortius.chunkbychunk.common.blockEntities.AbstractSpawnChunkBlockEntity.serverTick(AbstractSpawnChunkBlockEntity.java:63) ~[ChunkByChunk-forge-1.18.2-1.9.1.jar%2363!/:1.9.1] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[client-1.18.2-20220404.173914-srg.jar%23160!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:766) ~[client-1.18.2-20220404.173914-srg.jar%23160!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46463_(Level.java:476) ~[client-1.18.2-20220404.173914-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:beefix:Level,re:computing_frames,pl:accesstransformer:B,xf:fml:beefix:Level,re:classloading,pl:accesstransformer:B,xf:fml:beefix:Level,pl:mixin:APP:blockswap.mixins.json:MixinLevel,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:327) ~[client-1.18.2-20220404.173914-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architects_palette.mixins.json:ServerWorldMixin,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:APP:crafttweaker.mixins.json:common.transform.world.level.MixinServerLevel,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23160!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
```

Full crash report is attached.
[crash-2022-11-14_14.23.38-server.txt](https://github.com/immortius/chunkbychunk/files/10006732/crash-2022-11-14_14.23.38-server.txt)

**Comment by immortius** [comment] 2022-11-15 12:10
I'll look into this. I think it might be a compatibility issue with one of the mods you are using (nether islands perhaps) - so I'll see if that can be improved.

**Comment by immortius** [comment] 2022-11-17 11:14
Well, I was unable to reproduce with just nether islands. If you could determine a minimum set of mods that reproduces the issue that would be helpful - in the meantime I will add some extra logging and attempt to make the involved code more robust, because I can see it makes some potentially unsound assumptions. Just won't be able to test if it is fixing the issue.

**Comment by immortius** [comment] 2023-01-06 00:44
I've made the changes to make the code more robust and log issues some versions ago, otherwise haven't been able to reproduce so closing for now

**Closed by immortius** 2023-01-06 00:44 UTC
Labels: compatibility
