### ISSUE TITLE
Chunk Spawner Not Working

### ISSUE THREAD

**Issue by KintsugiKitten** [immortius/chunkbychunk#10] opened 2022-06-10 01:06 UTC
Is there some sort of timer for the Chunk Spawner to work? I placed it next to an empty chunk and intereacted. The block made a sound and disappeared, but no chunk appeared. I don't know what happened.

**Comment by immortius** [comment] 2022-06-10 07:52
There is a timer but it is near-instantaneous (at least for the blocks, animals and villagers take a second or so). What version of the chunk by chunk are you using?

**Comment by KintsugiKitten** [comment] 2022-06-10 11:34
Minecraft 1.19. As far as I'm aware there's only one version for 1.19.

**Comment by immortius** [comment] 2022-06-11 01:12
Technically there's a fabric and a forge version. I've tested both and the chunk spawner worked for me in both... so I need more information :). 
Are you using fabric or forge or quilt?
Is this single player or on a server?
Are you using any other mods?
Is there any error appearing in the minecraft log? 

Cheers

**Comment by KintsugiKitten** [comment] 2022-06-11 01:52
I'm using Fabric and my modlist includes a few mods that I think are likely to interfere. I'm using Oh, The Biomes and Biome Makeover. I also have Cave Enhancements, Croptopia, Terra blender, which I think is a dependency for Biome Makeover, there's Graveyard, and... I think that's it for the mods that are likely to alter world generation. Looking through the log files of the (single player) world reveals no clues to me as to what is causing the issue. I would send a log file but I have temporarily deactivated CBC and have encountered more errors with unrelated mods. To be expected of course, what with how little time devs have had to adapt to any coding changes in 1.19.

**Comment by immortius** [comment] 2022-06-11 02:48
Hmm, I tested with the mods you listed and it all seemed to function correctly. Must be a more obscure incompatibility. I guess let me know if you look into it again and obtain further information.

**Comment by KintsugiKitten** [comment] 2022-06-11 03:15
Of course! Thank you for taking the time to check.

**Comment by KintsugiKitten** [comment] 2022-06-12 02:12
I still haven't identified the source but I've discovered that the mod does work... but only on the world's first loading. If I save and quit, then reload again, it stops being able to spawn new chunks.

**Comment by immortius** [comment] 2022-06-12 09:46
I've reproduced using just chunk by chunk. It is fabric specific - the forge version works fine. It looks like under fabric the existence of custom dimensions is not being saved or loaded, so the chunk spawner cannot find the generation dimension to spawn from. Since the same approach works under forge it might be a fabric bug rather than a mod bug, will investigate further.

**Comment by immortius** [comment] 2022-06-13 01:32
Fixed in 1.8.3

**Closed by immortius** 2022-06-13 01:32 UTC
Labels: bug, fabric, mc-1.19, 1.8.3

**Comment by immortius** [comment] 2022-10-11 07:15
There's a forge version and a fabric version.
